project:
  type: website
  output-dir: "."

website:
  title: "Taylor Johnson"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: Resume.pdf
      - text: Python Data Analysis
        menu:
        - text: Python Basics
          href: basic-python-intro.ipynb
        - text: Python Basics with Pandas
          href: danl-210-quarto-py-only.qmd
        - text: Using Python and R Together
          href: danl-210-quarto-reticulate.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: cyborg
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
